# Generated by Django 2.0.5 on 2019-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='D:\\ML\\workspace\\webchat\\UserManager\\media\\headImg\\defaultAvatar.jpg', upload_to='D:\\ML\\workspace\\webchat\\UserManager\\media\\headImg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
